In [81]:
import pandas as pd
import os
import glob

In [83]:
path = os.getcwd() + '/Dataset_new/'

In [79]:
filename = 'udaya_resort.csv'
hotelname = 'The Udaya Resort & Spa'

In [82]:
df = pd.read_csv(path+filename)
df = df.drop(columns='Unnamed: 0')
df.insert(loc=0, column='hotel', value=hotelname)
df.to_csv('Dataset_new/'+filename)
df

,hotel,review,stars
0,The Udaya Resort & Spa,"Stafnya sangat ramah, pegawainya semuanya mene...",5
1,The Udaya Resort & Spa,"Stafnya ramah, semua yg diminta segera disiapk...",5
2,The Udaya Resort & Spa,"Sangat mengesankan nginap di the udaya resort,...",5
3,The Udaya Resort & Spa,Villa yang sangat luar biasa dari segi pelayan...,5
4,The Udaya Resort & Spa,"Kamar dan pelayanan sangat baik, cocok untuk p...",5
...,...,...,...
268,The Udaya Resort & Spa,Villa pribadi yang menakjubkan dengan kolam re...,5
269,The Udaya Resort & Spa,"Hotel Terbaik di Bali untuk bulan madu Anda, c...",5
270,The Udaya Resort & Spa,Udaya Resort and Spa adalah tempat yang cocok ...,4
271,The Udaya Resort & Spa,Resort yang luar biasa dengan Layanan Premium ...,5
272,The Udaya Resort & Spa,Ini adalah pertama kalinya saya datang ke Ubud...,5

In [84]:
# Combine

hotel_csv = os.path.join(path, '*.csv')
joined_review = glob.glob(hotel_csv)

hotel_df = pd.concat(map(pd.read_csv, joined_review), ignore_index=True)

In [86]:
stemed = pd.read_csv('stemmed_review.csv')

In [89]:
hotel_df

,Unnamed: 0,hotel,review,stars
0,0,Adiwana Bisma,"Liburan keluarga yg nyaman, kolam renang yg ba...",5
1,1,Adiwana Bisma,Hotelnya bagus banget dan pelayanannya sangat ...,5
2,2,Adiwana Bisma,Saya menginap di adiwana bisma bersama pasanga...,5
3,3,Adiwana Bisma,"hotelnya bagus banget, bersih dan lengkap fasi...",5
4,4,Adiwana Bisma,Weekend di Adiwana bisma stay selama two night...,5
...,...,...,...,...
21672,268,The Udaya Resort & Spa,Villa pribadi yang menakjubkan dengan kolam re...,5
21673,269,The Udaya Resort & Spa,"Hotel Terbaik di Bali untuk bulan madu Anda, c...",5
21674,270,The Udaya Resort & Spa,Udaya Resort and Spa adalah tempat yang cocok ...,4
21675,271,The Udaya Resort & Spa,Resort yang luar biasa dengan Layanan Premium ...,5
21676,272,The Udaya Resort & Spa,Ini adalah pertama kalinya saya datang ke Ubud...,5

In [90]:
stemed

,Unnamed: 0,review,stars,tokenized,no_slang,stemmed
0,0,"liburan keluarga yg nyaman, kolam renang yg ba...",5,"['liburan', 'keluarga', 'yg', 'nyaman', 'kolam...","['liburan', 'keluarga', 'yang', 'nyaman', 'kol...","['libur', 'keluarga', 'yang', 'nyaman', 'kolam..."
1,1,hotelnya bagus banget dan pelayanannya sangat ...,5,"['hotelnya', 'bagus', 'banget', 'dan', 'pelaya...","['hotelnya', 'bagus', 'banget', 'dan', 'pelaya...","['hotel', 'bagus', 'banget', 'dan', 'layan', '..."
2,2,saya menginap di adiwana bisma bersama pasanga...,5,"['saya', 'menginap', 'di', 'adiwana', 'bisma',...","['saya', 'menginap', 'di', 'adiwana', 'bisma',...","['saya', 'inap', 'di', 'adiwana', 'bisma', 'sa..."
3,3,"hotelnya bagus banget, bersih dan lengkap fasi...",5,"['hotelnya', 'bagus', 'banget', 'bersih', 'dan...","['hotelnya', 'bagus', 'banget', 'bersih', 'dan...","['hotel', 'bagus', 'banget', 'bersih', 'dan', ..."
4,4,weekend di adiwana bisma stay selama two night...,5,"['weekend', 'di', 'adiwana', 'bisma', 'stay', ...","['weekend', 'di', 'adiwana', 'bisma', 'stay', ...","['weekend', 'di', 'adiwana', 'bisma', 'stay', ..."
...,...,...,...,...,...,...
21678,21678,villa pribadi yang menakjubkan dengan kolam re...,5,"['villa', 'pribadi', 'yang', 'menakjubkan', 'd...","['villa', 'pribadi', 'yang', 'menakjubkan', 'd...","['villa', 'pribadi', 'yang', 'takjub', 'dengan..."
21679,21679,"hotel terbaik di bali untuk bulan madu anda, c...",5,"['hotel', 'terbaik', 'di', 'bali', 'untuk', 'b...","['hotel', 'terbaik', 'di', 'bali', 'untuk', 'b...","['hotel', 'baik', 'di', 'bal', 'untuk', 'bulan..."
21680,21680,udaya resort and spa adalah tempat yang cocok ...,4,"['udaya', 'resort', 'and', 'spa', 'adalah', 't...","['udaya', 'resort', 'and', 'spa', 'adalah', 't...","['udaya', 'resort', 'and', 'spa', 'adalah', 't..."
21681,21681,resort yang luar biasa dengan layanan premium ...,5,"['resort', 'yang', 'luar', 'biasa', 'dengan', ...","['resort', 'yang', 'luar', 'biasa', 'dengan', ...","['resort', 'yang', 'luar', 'biasa', 'dengan', ..."
21682,21682,ini adalah pertama kalinya saya datang ke ubud...,5,"['ini', 'adalah', 'pertama', 'kalinya', 'saya'...","['ini', 'adalah', 'pertama', 'kalinya', 'saya'...","['ini', 'adalah', 'pertama', 'kali', 'saya', '..."

In [92]:
pd.concat(g for _, g in hotel_df.groupby("review") if len(g) > 1)

,Unnamed: 0,hotel,review,stars
3781,231,AYANA Resort Bali,Ijinkan saya mengatakan bahwa meskipun kami ti...,5
18640,236,Rimba by AYANA Bali,Ijinkan saya mengatakan bahwa meskipun kami ti...,5
1076,445,Alaya Resort Ubud,Ini adalah jauh salah satu resor/Hotel yang lu...,5
3306,675,Amnaya Resort Kuta,Ini adalah jauh salah satu resor/Hotel yang lu...,5
2970,339,Amnaya Resort Kuta,"Kesan pertama Alaya resort kuta, sebuah hotel ...",5
2971,340,Amnaya Resort Kuta,"Kesan pertama Alaya resort kuta, sebuah hotel ...",5

In [94]:
pd.concat(g for _, g in stemed.groupby("review") if len(g) > 1)

,Unnamed: 0,review,stars,tokenized,no_slang,stemmed
3785,3785,ijinkan saya mengatakan bahwa meskipun kami ti...,5,"['ijinkan', 'saya', 'mengatakan', 'bahwa', 'me...","['ijinkan', 'saya', 'mengatakan', 'bahwa', 'me...","['ijinkan', 'saya', 'kata', 'bahwa', 'meski', ..."
3786,3786,ijinkan saya mengatakan bahwa meskipun kami ti...,5,"['ijinkan', 'saya', 'mengatakan', 'bahwa', 'me...","['ijinkan', 'saya', 'mengatakan', 'bahwa', 'me...","['ijinkan', 'saya', 'kata', 'bahwa', 'meski', ..."
3787,3787,ijinkan saya mengatakan bahwa meskipun kami ti...,5,"['ijinkan', 'saya', 'mengatakan', 'bahwa', 'me...","['ijinkan', 'saya', 'mengatakan', 'bahwa', 'me...","['ijinkan', 'saya', 'kata', 'bahwa', 'meski', ..."
3788,3788,ijinkan saya mengatakan bahwa meskipun kami ti...,5,"['ijinkan', 'saya', 'mengatakan', 'bahwa', 'me...","['ijinkan', 'saya', 'mengatakan', 'bahwa', 'me...","['ijinkan', 'saya', 'kata', 'bahwa', 'meski', ..."
1076,1076,ini adalah jauh salah satu resor/hotel yang lu...,5,"['ini', 'adalah', 'jauh', 'salah', 'satu', 're...","['ini', 'adalah', 'jauh', 'salah', 'satu', 're...","['ini', 'adalah', 'jauh', 'salah', 'satu', 're..."
1077,1077,ini adalah jauh salah satu resor/hotel yang lu...,5,"['ini', 'adalah', 'jauh', 'salah', 'satu', 're...","['ini', 'adalah', 'jauh', 'salah', 'satu', 're...","['ini', 'adalah', 'jauh', 'salah', 'satu', 're..."
1078,1078,ini adalah jauh salah satu resor/hotel yang lu...,5,"['ini', 'adalah', 'jauh', 'salah', 'satu', 're...","['ini', 'adalah', 'jauh', 'salah', 'satu', 're...","['ini', 'adalah', 'jauh', 'salah', 'satu', 're..."
1079,1079,ini adalah jauh salah satu resor/hotel yang lu...,5,"['ini', 'adalah', 'jauh', 'salah', 'satu', 're...","['ini', 'adalah', 'jauh', 'salah', 'satu', 're...","['ini', 'adalah', 'jauh', 'salah', 'satu', 're..."
2973,2973,"kesan pertama alaya resort kuta, sebuah hotel ...",5,"['kesan', 'pertama', 'alaya', 'resort', 'kuta'...","['kesan', 'pertama', 'alaya', 'resort', 'kuta'...","['kesan', 'pertama', 'alaya', 'resort', 'kuta'..."
2974,2974,"kesan pertama alaya resort kuta, sebuah hotel ...",5,"['kesan', 'pertama', 'alaya', 'resort', 'kuta'...","['kesan', 'pertama', 'alaya', 'resort', 'kuta'...","['kesan', 'pertama', 'alaya', 'resort', 'kuta'..."
2975,2975,"kesan pertama alaya resort kuta, sebuah hotel ...",5,"['kesan', 'pertama', 'alaya', 'resort', 'kuta'...","['kesan', 'pertama', 'alaya', 'resort', 'kuta'...","['kesan', 'pertama', 'alaya', 'resort', 'kuta'..."
2976,2976,"kesan pertama alaya resort kuta, sebuah hotel ...",5,"['kesan', 'pertama', 'alaya', 'resort', 'kuta'...","['kesan', 'pertama', 'alaya', 'resort', 'kuta'...","['kesan', 'pertama', 'alaya', 'resort', 'kuta'..."

In [103]:
hotel_df = hotel_df.drop_duplicates(subset=['review'])

In [108]:
stemed.shape

(21674, 5)

In [107]:
hotel_df = hotel_df.drop(hotel_df.columns[0], axis = 1)
stemed = stemed.drop(stemed.columns[0], axis = 1)

In [109]:
hotel_df['review'] = hotel_df['review'].str.lower()

In [110]:
hotel_df

,hotel,review,stars
0,Adiwana Bisma,"liburan keluarga yg nyaman, kolam renang yg ba...",5
1,Adiwana Bisma,hotelnya bagus banget dan pelayanannya sangat ...,5
2,Adiwana Bisma,saya menginap di adiwana bisma bersama pasanga...,5
3,Adiwana Bisma,"hotelnya bagus banget, bersih dan lengkap fasi...",5
4,Adiwana Bisma,weekend di adiwana bisma stay selama two night...,5
...,...,...,...
21672,The Udaya Resort & Spa,villa pribadi yang menakjubkan dengan kolam re...,5
21673,The Udaya Resort & Spa,"hotel terbaik di bali untuk bulan madu anda, c...",5
21674,The Udaya Resort & Spa,udaya resort and spa adalah tempat yang cocok ...,4
21675,The Udaya Resort & Spa,resort yang luar biasa dengan layanan premium ...,5
21676,The Udaya Resort & Spa,ini adalah pertama kalinya saya datang ke ubud...,5

In [111]:
hotel_df = hotel_df.drop(hotel_df.columns[-1], axis = 1)

In [112]:
hotel_df

,hotel,review
0,Adiwana Bisma,"liburan keluarga yg nyaman, kolam renang yg ba..."
1,Adiwana Bisma,hotelnya bagus banget dan pelayanannya sangat ...
2,Adiwana Bisma,saya menginap di adiwana bisma bersama pasanga...
3,Adiwana Bisma,"hotelnya bagus banget, bersih dan lengkap fasi..."
4,Adiwana Bisma,weekend di adiwana bisma stay selama two night...
...,...,...
21672,The Udaya Resort & Spa,villa pribadi yang menakjubkan dengan kolam re...
21673,The Udaya Resort & Spa,"hotel terbaik di bali untuk bulan madu anda, c..."
21674,The Udaya Resort & Spa,udaya resort and spa adalah tempat yang cocok ...
21675,The Udaya Resort & Spa,resort yang luar biasa dengan layanan premium ...
21676,The Udaya Resort & Spa,ini adalah pertama kalinya saya datang ke ubud...

In [138]:
result = pd.merge(stemed, hotel_df, on='review')

In [139]:
result

,review,stars,tokenized,no_slang,stemmed,hotel
0,"liburan keluarga yg nyaman, kolam renang yg ba...",5,"['liburan', 'keluarga', 'yg', 'nyaman', 'kolam...","['liburan', 'keluarga', 'yang', 'nyaman', 'kol...","['libur', 'keluarga', 'yang', 'nyaman', 'kolam...",Adiwana Bisma
1,hotelnya bagus banget dan pelayanannya sangat ...,5,"['hotelnya', 'bagus', 'banget', 'dan', 'pelaya...","['hotelnya', 'bagus', 'banget', 'dan', 'pelaya...","['hotel', 'bagus', 'banget', 'dan', 'layan', '...",Adiwana Bisma
2,saya menginap di adiwana bisma bersama pasanga...,5,"['saya', 'menginap', 'di', 'adiwana', 'bisma',...","['saya', 'menginap', 'di', 'adiwana', 'bisma',...","['saya', 'inap', 'di', 'adiwana', 'bisma', 'sa...",Adiwana Bisma
3,"hotelnya bagus banget, bersih dan lengkap fasi...",5,"['hotelnya', 'bagus', 'banget', 'bersih', 'dan...","['hotelnya', 'bagus', 'banget', 'bersih', 'dan...","['hotel', 'bagus', 'banget', 'bersih', 'dan', ...",Adiwana Bisma
4,weekend di adiwana bisma stay selama two night...,5,"['weekend', 'di', 'adiwana', 'bisma', 'stay', ...","['weekend', 'di', 'adiwana', 'bisma', 'stay', ...","['weekend', 'di', 'adiwana', 'bisma', 'stay', ...",Adiwana Bisma
...,...,...,...,...,...,...
21669,villa pribadi yang menakjubkan dengan kolam re...,5,"['villa', 'pribadi', 'yang', 'menakjubkan', 'd...","['villa', 'pribadi', 'yang', 'menakjubkan', 'd...","['villa', 'pribadi', 'yang', 'takjub', 'dengan...",The Udaya Resort & Spa
21670,"hotel terbaik di bali untuk bulan madu anda, c...",5,"['hotel', 'terbaik', 'di', 'bali', 'untuk', 'b...","['hotel', 'terbaik', 'di', 'bali', 'untuk', 'b...","['hotel', 'baik', 'di', 'bal', 'untuk', 'bulan...",The Udaya Resort & Spa
21671,udaya resort and spa adalah tempat yang cocok ...,4,"['udaya', 'resort', 'and', 'spa', 'adalah', 't...","['udaya', 'resort', 'and', 'spa', 'adalah', 't...","['udaya', 'resort', 'and', 'spa', 'adalah', 't...",The Udaya Resort & Spa
21672,resort yang luar biasa dengan layanan premium ...,5,"['resort', 'yang', 'luar', 'biasa', 'dengan', ...","['resort', 'yang', 'luar', 'biasa', 'dengan', ...","['resort', 'yang', 'luar', 'biasa', 'dengan', ...",The Udaya Resort & Spa
21673,ini adalah pertama kalinya saya datang ke ubud...,5,"['ini', 'adalah', 'pertama', 'kalinya', 'saya'...","['ini', 'adalah', 'pertama', 'kalinya', 'saya'...","['ini', 'adalah', 'pertama', 'kali', 'saya', '...",The Udaya Resort & Spa

In [140]:
new_cols = ['hotel', 'review', 'stars', 'tokenized', 'no_slang', 'stemmed', ]
result = result[new_cols]

In [141]:
result

,hotel,review,stars,tokenized,no_slang,stemmed
0,Adiwana Bisma,"liburan keluarga yg nyaman, kolam renang yg ba...",5,"['liburan', 'keluarga', 'yg', 'nyaman', 'kolam...","['liburan', 'keluarga', 'yang', 'nyaman', 'kol...","['libur', 'keluarga', 'yang', 'nyaman', 'kolam..."
1,Adiwana Bisma,hotelnya bagus banget dan pelayanannya sangat ...,5,"['hotelnya', 'bagus', 'banget', 'dan', 'pelaya...","['hotelnya', 'bagus', 'banget', 'dan', 'pelaya...","['hotel', 'bagus', 'banget', 'dan', 'layan', '..."
2,Adiwana Bisma,saya menginap di adiwana bisma bersama pasanga...,5,"['saya', 'menginap', 'di', 'adiwana', 'bisma',...","['saya', 'menginap', 'di', 'adiwana', 'bisma',...","['saya', 'inap', 'di', 'adiwana', 'bisma', 'sa..."
3,Adiwana Bisma,"hotelnya bagus banget, bersih dan lengkap fasi...",5,"['hotelnya', 'bagus', 'banget', 'bersih', 'dan...","['hotelnya', 'bagus', 'banget', 'bersih', 'dan...","['hotel', 'bagus', 'banget', 'bersih', 'dan', ..."
4,Adiwana Bisma,weekend di adiwana bisma stay selama two night...,5,"['weekend', 'di', 'adiwana', 'bisma', 'stay', ...","['weekend', 'di', 'adiwana', 'bisma', 'stay', ...","['weekend', 'di', 'adiwana', 'bisma', 'stay', ..."
...,...,...,...,...,...,...
21669,The Udaya Resort & Spa,villa pribadi yang menakjubkan dengan kolam re...,5,"['villa', 'pribadi', 'yang', 'menakjubkan', 'd...","['villa', 'pribadi', 'yang', 'menakjubkan', 'd...","['villa', 'pribadi', 'yang', 'takjub', 'dengan..."
21670,The Udaya Resort & Spa,"hotel terbaik di bali untuk bulan madu anda, c...",5,"['hotel', 'terbaik', 'di', 'bali', 'untuk', 'b...","['hotel', 'terbaik', 'di', 'bali', 'untuk', 'b...","['hotel', 'baik', 'di', 'bal', 'untuk', 'bulan..."
21671,The Udaya Resort & Spa,udaya resort and spa adalah tempat yang cocok ...,4,"['udaya', 'resort', 'and', 'spa', 'adalah', 't...","['udaya', 'resort', 'and', 'spa', 'adalah', 't...","['udaya', 'resort', 'and', 'spa', 'adalah', 't..."
21672,The Udaya Resort & Spa,resort yang luar biasa dengan layanan premium ...,5,"['resort', 'yang', 'luar', 'biasa', 'dengan', ...","['resort', 'yang', 'luar', 'biasa', 'dengan', ...","['resort', 'yang', 'luar', 'biasa', 'dengan', ..."
21673,The Udaya Resort & Spa,ini adalah pertama kalinya saya datang ke ubud...,5,"['ini', 'adalah', 'pertama', 'kalinya', 'saya'...","['ini', 'adalah', 'pertama', 'kalinya', 'saya'...","['ini', 'adalah', 'pertama', 'kali', 'saya', '..."

In [143]:
result.to_csv('stemmed.csv')